name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: microsoft/setup-msbuild@v1.1
    - run: build.bat
      shell: cmd
    - uses: actions/upload-artifact@v4
      with:
        name: VNTranslationTools
        path: Build
